version: "3"

services:
  mongodb:
    container_name: db
    image: mongo
    ports:
    - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: rootpass
  mongo-express:
    container_name: panel
    image: mongo-express
    ports:
    - "8080:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpass
      ME_CONFIG_MONGODB_SERVER: mongodb
  app:
    container_name: app
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
    - "3000:3000"