version: "3"

services:
  mongodb:
    container_name: db
    image: mongo
    ports:
    - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    volumes:
      - docker-tech-world:/data/db
  mongo-express:
    container_name: panel
    image: mongo-express
    ports:
    - "8080:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpass
      ME_CONFIG_MONGODB_SERVER: mongodb
  app:
    container_name: app
    image: 208426166126.dkr.ecr.eu-central-1.amazonaws.com/my-app:2.0
    ports:
    - "3000:3000"
volumes:
  docker-tech-world:
    driver: local